export type ItemMenu = {
    id: string,
    position: number,
    name: string,
    link: string,
    hidden?: boolean,
    menuItemList?: ItemMenu[],
    groupLink?: string,
    key?: string,
    icon?: string
    groupId?: string,
    groupName?: string,
    groupIcon?: string,
    groupKey?:string,
}
export const menuData: ItemMenu[] = [
  {
    id: 'login',
    position: 1,
    name: 'Đăng nhập',
    link: '/dang-nhap',
  },
  {
    id: 'privacypolicy',
    position: 2,
    name: 'Privacy Policy',
    link: '/privacy-policy',
  },
  {
    id: 'home',
    position: 3,
    name: 'Home',
    link: '/home',
    menuItemList: 
    [
      {
        icon: 'user-list',
        groupLink: '/managers',
        id: 'managers',
        position: 0,
        key: 'managers',
        link: '/managers',
        name: 'Quản lý tài khoản',
      },
      {
        groupId: 'cameraGroup',
        groupKey: 'cameraGroup',
        groupName: 'Xem theo nhóm Camera',
        groupIcon: 'details',
        icon: 'details',
        groupLink: '/camera-group',
        id: 'listCameraGroup',
        position: 0,
        key: 'listCameraGroup',
        link: '/camera-group/list',
        name: 'Danh sách nhóm',
      },
      {
        groupId: 'cameraGroup',
        groupName: 'Xem theo nhóm Camera',
        groupLink: '/camera-group',
        groupKey: 'cameraGroup',
        groupIcon: 'details',
        id: 'showCameraGroup',
        key: 'showCameraGroup',
        position: 1,
        link: '/camera-group/show',
        name: 'Xem',
        hidden: true,
      },
      {
        groupId: 'cameraGroup',
        groupName: 'Xem theo nhóm Camera',
        groupLink: '/cameraGroup',
        groupKey: 'cameraGroup',
        groupIcon: 'details',
        id: 'addCameraGroup',
        key: 'addCameraGroup',
        position: 2,
        link: '/camera-group/add',
        name: 'Thêm',
        hidden: true,
      },
      {
        groupId: 'cameraGroup',
        groupName: 'Xem theo nhóm Camera',
        groupLink: '/camera-group',
        groupKey: 'cameraGroup',
        groupIcon: 'details',
        id: 'editCameraGroup',
        key: 'editCameraGroup',
        position: 3,
        link: '/camera-group/edit',
        name: 'Sửa',
        hidden: true,
      },
      {
        id: 'liveview',
        position: 4,
        link: '/liveview',
        name: 'Xem trực tiếp',
        icon: 'liveview',
        key: 'liveview',
      },
      {
        id: 'listregisuser',
        position: 6,
        link: '/list-user-regis',
        name: 'Danh sách người đăng ký',
        icon: 'list-user',
        key: 'listregisuser',
      },
      {
        id: 'ailiveview',
        position: 6,
        link: '/ai-liveview',
        name: 'Xem trực tiếp sự kiện',
        icon: 'ai-liveview',
        key: 'ailiveview',
      },
      {
        id: 'aiSettings',
        position: 6,
        link: '/ai-settings',
        name: 'Cấu hình sự kiện',
        icon: 'gear',
        key: 'aiSettings',
      },
      {
        groupId: 'timekeepings',
        groupName: 'Quản lý chấm công',
        groupLink: '/timekeepings',
        groupKey: 'timekeepings',
        groupIcon: 'timekeepings',
        id: 'staff-management',
        position: 1,
        link: '/staff-management',
        name: 'Nhân viên',
        key: 'staffManagement',
        icon: 'list-user',
      },
      {
        groupId: 'timekeepings',
        groupName: 'Quản lý chấm công',
        groupLink: '/timekeepings',
        groupIcon: 'timekeepings',
        groupKey: 'timekeepings',
        id: 'shift-management',
        position: 2,
        link: '/shift-management',
        name: 'Ca trực',
        key: 'shiftManagement',
        icon: 'clock',
      },

      {
        groupId: 'timekeepings',
        groupName: 'Quản lý chấm công',
        groupLink: '/timekeepings',
        groupIcon: 'timekeepings',
        groupKey: 'timekeepings',
        id: 'timekeeping-realtime',
        position: 3,
        link: '/timekeeping-realtime',
        name: 'Chấm công',
        key: 'timekeepingRealtime',
        icon: 'realtime-face',
      },
      {
        groupId: 'timekeepings',
        groupName: 'Quản lý chấm công',
        groupLink: '/timekeepings',
        groupIcon: 'timekeepings',
        groupKey: 'timekeepings',
        id: 'timekeeping-allocation',
        position: 3,
        link: '/timekeeping-allocation',
        name: 'Phân quyền truy cập',
        key: 'timekeepingAllocation',
        icon: 'group-users',
      },
      {
        groupId: 'timekeepings',
        groupName: 'Quản lý chấm công',
        groupLink: '/timekeepings',
        groupIcon: 'timekeepings',
        groupKey: 'timekeepings',
        id: 'timekeeping-history',
        position: 4,
        link: '/timekeeping-history',
        name: 'Lịch sử',
        key: 'timekeepingHistory',
        icon: 'history',
      },
      {
        groupId: 'timekeepings',
        groupName: 'Quản lý chấm công',
        groupLink: '/timekeepings',
        groupIcon: 'timekeepings',
        groupKey: 'timekeepings',
        id: 'timekeeping-report',
        position: 4,
        link: '/timekeeping-report',
        name: 'Báo cáo',
        key: 'timekeepingReport',
        icon: 'new-report',
      },
      {
        groupId: 'timekeepings',
        groupName: 'Quản lý chấm công',
        groupLink: '/timekeepings',
        groupIcon: 'timekeepings',
        groupKey: 'timekeepings',
        id: 'timekeeping-statistic',
        position: 6,
        link: '/timekeeping-statistic',
        name: 'Thống kê',
        key: 'timekeepingStatistic',
        icon: 'chart-icon',
      },
      {
        groupId: 'timekeepings',
        groupName: 'Quản lý chấm công',
        groupLink: '/timekeepings',
        groupIcon: 'timekeepings',
        groupKey: 'timekeepings',
        id: 'timekeeping-access-camera',
        position: 3,
        link: '/branch-permission',
        name: 'Quyền chi nhánh',
        key: 'branchPermission',
        icon: 'tree-structure',
      },
      {
        id: 'aiSearch',
        position: 6,
        link: '/ai-search',
        name: 'Tìm kiếm sự kiện',
        icon: 'search',
        key: 'aiSearch',
      },
      {
        id: 'warning',
        position: 6,
        link: '/ai-warning',
        name: 'Cảnh báo sự kiện',
        icon: 'siren',
        key: 'aiWarning',
      },
      {
        id: 'playback',
        position: 5,
        link: '/playback',
        name: 'Xem chi tiết',
        icon: 'playback',
        key: 'playback',
      },
      {
        id: 'camera_find_camera_by_link',
        position: 5,
        link: '/xem-duong-dan',
        name: 'Xem lại đường dẫn',
        hidden: true,
        key: 'findCameraByLink',
      },
      {
        id: 'device-management',
        position: 10,
        link: '/devices-management',
        name: 'Quản lý thiết bị',
        icon: 'cpu',
        key: 'deviceManagement',
      },
      {
        id: 'statistic-event',
        position: 10,
        link: '/statistic-event',
        name: 'Thông kê sự kiện',
        icon: 'chart-icon',
        key: 'statisticEvent',
      },
      {
        id: 'Account',
        position: 1,
        link: '/account',
        name: 'Thông tin cá nhân',
        icon: 'bullet-menu',
        hidden: true,
        key: 'account',
      },
      {
        id: 'minimap',
        position: 1,
        link: '/minimap',
        name: 'Minimap',
        icon: 'map-trifold',
        key: 'minimap',
      },

      {
        groupId: 'liscenseplate',
        groupLink: '/liscenseplates',
        groupName: 'Biển số xe',
        groupKey: 'liscenseplate',
        groupIcon: 'plate',
        id: 'vehicle-show',
        position: 1,
        link: '/vehicle-show',
        name: 'VehicleShow',
        key: 'vehicle-show',
        icon: 'liveview',
      },

      {
        groupId: 'liscenseplate',
        groupLink: '/liscenseplates',
        groupName: 'Biển số xe',
        groupKey: 'liscenseplate',
        groupIcon: 'plate',
        id: 'vehicle-noti-real-time',
        position: 2,
        link: '/vehicle-noti-real-time',
        name: 'Xem danh sách thông báo',
        key: 'vehicle-noti-real-time',
        icon: 'siren',
      },
      {
        groupId: 'liscenseplate',
        groupLink: '/liscenseplates',
        groupName: 'Biển số xe',
        groupKey: 'liscenseplate',
        groupIcon: 'plate',
        id: 'vehicle-info',
        position: 3,
        link: '/vehicle-info',
        name: 'Tra thông tin biển số',
        key: 'vehicle-info',
        icon: 'search',
      },
      {
        groupId: 'liscenseplate',
        groupLink: '/liscenseplates',
        groupName: 'Biển số xe',
        groupKey: 'liscenseplate',
        groupIcon: 'plate',
        id: 'vehicle-find',
        position: 4,
        link: '/vehicle-find',
        name: 'Tra lộ trình biển số',
        key: 'vehicle-find',
        icon: 'location',
      },
      {
        groupId: 'liscenseplate',
        groupLink: '/liscenseplates',
        groupName: 'Biển số xe',
        groupKey: 'liscenseplate',
        groupIcon: 'plate',
        id: 'vehicle-real-time',
        position: 5,
        link: '/vehicle-real-time',
        name: 'Xem danh sách biển số thời gian thực',
        key: 'vehicle-real-time',
        icon: 'list',
      },
      {
        groupId: 'liscenseplate',
        groupLink: '/liscenseplates',
        groupName: 'Biển số xe',
        groupKey: 'liscenseplate',
        groupIcon: 'plate',
        id: 'vehicle-info-time',
        position: 6,
        link: '/vehicle-info-time',
        name: 'Lấy danh sách biển số theo giờ',
        key: 'vehicle-info-time',
        icon: 'list-time',
      },
      {
        groupId: 'liscenseplate',
        groupLink: '/liscenseplates',
        groupName: 'Biển số xe',
        groupKey: 'liscenseplate',
        groupIcon: 'plate',
        id: 'vehicle-black-list',
        position: 7,
        link: '/vehicle-black-list',
        name: 'Danh sách chú ý',
        key: 'vehicle-black-list',
        icon: 'list',
      },
      {
        groupId: 'liscenseplate',
        groupLink: '/liscenseplates',
        groupName: 'Biển số xe',
        groupKey: 'liscenseplate',
        groupIcon: 'plate',
        id: 'vehicle-white-list',
        position: 8,
        link: '/vehicle-white-list',
        name: 'Danh sách ưu tiên',
        key: 'vehicle-white-list',
        icon: 'list',
      },
      {
        groupId: 'liscenseplate',
        groupLink: '/liscenseplates',
        groupName: 'Biển số xe',
        groupKey: 'liscenseplate',
        groupIcon: 'plate',
        id: 'vehicle-type-statistic',
        position: 9,
        link: '/vehicle-type-statistic',
        name: 'Thống kê loại xe',
        key: 'vehicle-type-statistic',
        icon: 'chart-icon',
      },
      {
        groupId: 'liscenseplate',
        groupLink: '/liscenseplates',
        groupName: 'Biển số xe',
        groupKey: 'liscenseplate',
        groupIcon: 'plate',
        id: 'vehicle-time-statistic',
        position: 10,
        link: '/vehicle-time-statistic',
        name: 'Thống kê biển số',
        key: 'vehicle-time-statistic',
        icon: 'chart-icon',
      },
      // Traffic
      {
        groupId: 'traffic',
        groupName: 'Giao thông',
        groupLink: '/traffic',
        groupIcon: 'traffic',
        groupKey: 'traffic',
        id: 'traffic-statistic',
        position: 1,
        link: '/traffic-statistic',
        name: 'Thống kê',
        key: 'statistic',
        icon: 'realtime-face',
      },
      {
        groupId: 'traffic',
        groupName: 'Giao thông',
        groupLink: '/traffic',
        groupIcon: 'traffic',
        groupKey: 'traffic',
        id: 'traffic-map',
        position: 2,
        link: '/traffic-map',
        name: 'Bản đồ',
        key: 'map',
        icon: 'group-users',
      },
      {
        groupId: 'traffic',
        groupName: 'Giao thông',
        groupLink: '/traffic',
        groupIcon: 'traffic',
        groupKey: 'traffic',
        id: 'traffic-export',
        position: 4,
        link: '/traffic-export',
        name: 'Xuất',
        key: 'export',
        icon: 'history',
      },
    ],
  },
];
